-- db-kit sptest 樣本 schema（PostgreSQL）。單句一行結尾 `;`，整合測試逐句執行。
-- orders 的 identity 從 1000 起算：與 MSSQL（101）/ MySQL（500）刻意不同。
DROP SCHEMA IF EXISTS sptest CASCADE;
CREATE SCHEMA sptest;
CREATE TABLE sptest.customers (
  customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  credit NUMERIC(12,2) NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE sptest.products (
  product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC(12,2) NOT NULL,
  stock INT NOT NULL
);
CREATE TABLE sptest.orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  customer_id INT NOT NULL REFERENCES sptest.customers(customer_id),
  product_id INT NOT NULL REFERENCES sptest.products(product_id),
  qty INT NOT NULL,
  total NUMERIC(12,2) NOT NULL,
  status TEXT NOT NULL DEFAULT 'NEW',
  created_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE TABLE sptest.audit_log (
  audit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);
